version: 2.1
ros_steps: &ros_steps
  - restore_cache:
      keys:
        - <<parameters.ccache_prefix>>-{{ .Branch }}-{{ .Revision }}
        - <<parameters.ccache_prefix>>-{{ .Branch }}-
        - <<parameters.ccache_prefix>>-
  - run:
      # Install git and ssh before checkout. Because larger
      name: install git and ssh
      command: |
        apt update
        apt install -y git ssh ccache
        # Creat .ssh/config in order to disable host key prompt
         mkdir -p ~/.ssh
         echo "Host *" >> ~/.ssh/config
        echo "  StrictHostKeyChecking no" >> ~/.ssh/config
  - run:
      name: Larger ccache storage
      command: |
        ccache -M 5G
  - checkout
  - add_ssh_keys
  - run:
      name: update submodules (if needed)
      command: |
        git submodule update --init
  - run:
      name: Set Up Container
      command: |
        apt-get update -qq && apt-get install -y python-catkin-tools python-pip
  - run:
      name: Clone other repositories
      command: |
        wstool init --shallow
        if [ -n "${ROSINSTALL_FILE}" -a -e ${ROSINSTALL_FILE} ]; then
          cd ..
          wstool merge project/$ROSINSTALL_FILE
          wstool update -j10
        fi
  - run:
      name: rosdep install
      command: |
        source `find /opt/ros -name setup.bash | sort | head -1`
        rosdep update
        rosdep install --from-paths .. --ignore-src -rny || true
  - run:
      name: catkin init
      command: |
        cd ../..
        catkin init
        catkin config --extend /opt/ros/$ROS_DISTRO
  - run:
      name: Build
      command: |
        cd ../..
        catkin build --no-status -j4
  - run:
      name: Run Tests
      command: |
        source `find /opt/ros -name setup.bash | sort | head -1`
        cd ../..
        TARGET_PKGS=$(catkin_topological_order . --only-names)
        catkin run_tests -j4 --no-deps --no-status --summarize "${TARGET_PKGS[@]}"
        catkin_test_results
  - save_cache:
      key: <<parameters.ccache_prefix>>-{{ .Branch }}-{{ .Revision }}
      paths:
        - ~/.ccache

jobs:
  lint:
    docker:
      - image: gitaiinc/gitai-style
    steps:
      - checkout
      - add_ssh_keys
      - run: 'git clone git@github.com:GITAI/gitai_style.git /tmp/gitai_style --depth=1'
      - run: 'cd ~/project && /tmp/gitai_style/ci_scripts/review.sh || true'

  kinetic:
    docker:
      - image: gitaiinc/gitai-ci:kinetic
    steps: *ros_steps
    working_directory: ~/src/project
    environment:
      ROSINSTALL_FILE: .travis.rosinstall
      CC: ccache gcc
      CXX: ccache g++
    parameters:
      ccache_prefix:
        type: string
        default: cache-kinetic

  melodic:
    docker:
      - image: gitaiinc/gitai-ci:melodic
    steps: *ros_steps
    working_directory: ~/src/project
    environment:
      ROSINSTALL_FILE: .travis.rosinstall
      CC: ccache gcc
      CXX: ccache g++
    parameters:
      ccache_prefix:
        type: string
        default: cache-melodic

workflows:
  review:
    jobs:
      - lint
  tests:
    jobs:
      - kinetic
      - melodic
